name: jjideenschmiede/github-last-matching-ref
title: Fetch last matching GitHub reference
version: 1.0.0
description: |
  Fetches the last Git reference (branch or tag) from a GitHub repository
  that matches a specified pattern. The result is stored in an environment variable.
inputs:
  - env.input_repository:
      type: text
      required: true
      label: Repository
      description: |
        GitHub repository in "owner/repo" format (e.g., "JetBrains/teamcity-recipes").
  - env.input_ref:
      type: text
      required: true
      label: Reference Pattern
      description: |
        The Git reference pattern to match. Examples:
        - "heads/" - List all branches
        - "tags/" - List all tags
        - "heads/feature" - List branches starting with "feature"
        - "tags/v1." - List tags starting with "v1."
        - "heads/main" - Get specific branch "main"
      default: "tags"
  - env.input_github_access_token:
      type: password
      required: false
      label: GitHub Access Token
      description: |
        Optional GitHub personal access token for authenticated requests.
        Increases rate limits and allows access to private repositories.
  - env.input_variable_name:
      type: text
      required: false
      label: Environment Variable Name
      description: |
        The name of the environment variable to store the last matching reference.
      default: "GITHUB_LATEST_REF"
steps:
  - name: Fetch latest GitHub release version
    kotlin-script: !include src.main.kts
